### ISSUE TITLE
plan: ray.c와 put_object_utils 만 리팩토링 남음

### ISSUE THREAD

**Issue by sob2545** [sob2545/miniRT#7]
- [ ] utils 파일 노미넷에 맞게 고치기
 - [ ] get_uv에서 일반 plane과 cap, 기타 obj들과의 차이점

**Comment by Giromi** [comment]
atod 예외처리 나중에 과제 통과하고 다시 한번 만져보면 좋을듯...

atod는 범위를 실제 double max범위로 해놓고
atovec에서 정수 사이의 범위 만큼으로 하는게 좋지 않을까 생각...

example
```c
ft_strerror("err: exceed coordinate value range");
```
지금 위 의 예외처리는 나올 수 없음
